# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: education.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x64ucation.proto\"\xca\x08\n\rEducationData\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12!\n\x19oosr_pre0primary_age_male\x18\x04 \x01(\x05\x12#\n\x1boosr_pre0primary_age_female\x18\x05 \x01(\x05\x12\x1d\n\x15oosr_primary_age_male\x18\x06 \x01(\x05\x12\x1f\n\x17oosr_primary_age_female\x18\x07 \x01(\x05\x12%\n\x1doosr_lower_secondary_age_male\x18\x08 \x01(\x05\x12\'\n\x1foosr_lower_secondary_age_female\x18\t \x01(\x05\x12%\n\x1doosr_upper_secondary_age_male\x18\n \x01(\x05\x12\'\n\x1foosr_upper_secondary_age_female\x18\x0b \x01(\x05\x12$\n\x1c\x63ompletion_rate_primary_male\x18\x0c \x01(\x05\x12&\n\x1e\x63ompletion_rate_primary_female\x18\r \x01(\x05\x12,\n$completion_rate_lower_secondary_male\x18\x0e \x01(\x05\x12.\n&completion_rate_lower_secondary_female\x18\x0f \x01(\x05\x12,\n$completion_rate_upper_secondary_male\x18\x10 \x01(\x05\x12.\n&completion_rate_upper_secondary_female\x18\x11 \x01(\x05\x12%\n\x1dgrade_2_3_proficiency_reading\x18\x12 \x01(\x05\x12\"\n\x1agrade_2_3_proficiency_math\x18\x13 \x01(\x05\x12\'\n\x1fprimary_end_proficiency_reading\x18\x14 \x01(\x05\x12$\n\x1cprimary_end_proficiency_math\x18\x15 \x01(\x05\x12/\n\'lower_secondary_end_proficiency_reading\x18\x16 \x01(\x05\x12,\n$lower_secondary_end_proficiency_math\x18\x17 \x01(\x05\x12&\n\x1eyouth_15_24_literacy_rate_male\x18\x18 \x01(\x05\x12(\n youth_15_24_literacy_rate_female\x18\x19 \x01(\x05\x12\x12\n\nbirth_rate\x18\x1a \x01(\x01\x12*\n\"gross_primary_education_enrollment\x18\x1b \x01(\x01\x12+\n#gross_tertiary_education_enrollment\x18\x1c \x01(\x01\x12\x19\n\x11unemployment_rate\x18\x1d \x01(\x01\x42\x0bZ\t../commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'education_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t../common'
  _globals['_EDUCATIONDATA']._serialized_start=20
  _globals['_EDUCATIONDATA']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
